/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @dfinity/caffeine-bindgen@0.1.0-beta.7.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Badge = IDL.Record({
  'id' : IDL.Text,
  'communityId' : IDL.Text,
  'displayCode' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'claimCode' : IDL.Text,
  'imageUrl' : IDL.Text,
  'quantity' : IDL.Nat,
  'claimedCount' : IDL.Nat,
});
export const Community = IDL.Record({
  'id' : IDL.Text,
  'admin' : IDL.Principal,
  'name' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const UserBadge = IDL.Record({
  'communityId' : IDL.Text,
  'claimedAt' : IDL.Int,
  'badgeId' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addBadge' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
      [IDL.Text],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'claimBadge' : IDL.Func([IDL.Text], [IDL.Text], []),
  'createCommunity' : IDL.Func([IDL.Text], [IDL.Text], []),
  'getAdminBadgeAnalytics' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(Badge, IDL.Nat, IDL.Nat, IDL.Vec(IDL.Principal)))],
      ['query'],
    ),
  'getAdminBadgeClaimCodes' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
      ['query'],
    ),
  'getAdminBadgeClaimUrls' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
      ['query'],
    ),
  'getAllAvailableBadges' : IDL.Func([], [IDL.Vec(Badge)], ['query']),
  'getAllCommunities' : IDL.Func([], [IDL.Vec(Community)], ['query']),
  'getBadgesByCommunity' : IDL.Func([IDL.Text], [IDL.Vec(Badge)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getClaimCodeDetails' : IDL.Func([IDL.Text], [IDL.Opt(Badge)], ['query']),
  'getClaimStatus' : IDL.Func(
      [IDL.Text],
      [
        IDL.Record({
          'errorMessage' : IDL.Opt(IDL.Text),
          'isClaimed' : IDL.Bool,
          'badge' : IDL.Opt(Badge),
          'isValid' : IDL.Bool,
        }),
      ],
      ['query'],
    ),
  'getCommunityBadgeCount' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'getCommunityClaimUrls' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
      ['query'],
    ),
  'getMostRecentBadge' : IDL.Func([], [IDL.Opt(UserBadge)], ['query']),
  'getMostRecentBadgeDetails' : IDL.Func(
      [],
      [IDL.Opt(IDL.Tuple(UserBadge, IDL.Opt(Badge), IDL.Opt(Community)))],
      ['query'],
    ),
  'getTotalBadges' : IDL.Func([], [IDL.Nat], ['query']),
  'getTotalCommunities' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserBadgeCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserBadgeDetails' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(UserBadge, IDL.Opt(Badge)))],
      ['query'],
    ),
  'getUserBadges' : IDL.Func([], [IDL.Vec(UserBadge)], ['query']),
  'getUserBadgesByCommunity' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Vec(UserBadge)))],
      ['query'],
    ),
  'getUserCommunities' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getUserCreatedCommunities' : IDL.Func([], [IDL.Vec(Community)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isBadgeClaimedByUser' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'validateClaimCode' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Badge = IDL.Record({
    'id' : IDL.Text,
    'communityId' : IDL.Text,
    'displayCode' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'claimCode' : IDL.Text,
    'imageUrl' : IDL.Text,
    'quantity' : IDL.Nat,
    'claimedCount' : IDL.Nat,
  });
  const Community = IDL.Record({
    'id' : IDL.Text,
    'admin' : IDL.Principal,
    'name' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const UserBadge = IDL.Record({
    'communityId' : IDL.Text,
    'claimedAt' : IDL.Int,
    'badgeId' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addBadge' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
        [IDL.Text],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'claimBadge' : IDL.Func([IDL.Text], [IDL.Text], []),
    'createCommunity' : IDL.Func([IDL.Text], [IDL.Text], []),
    'getAdminBadgeAnalytics' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(Badge, IDL.Nat, IDL.Nat, IDL.Vec(IDL.Principal)))],
        ['query'],
      ),
    'getAdminBadgeClaimCodes' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
        ['query'],
      ),
    'getAdminBadgeClaimUrls' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
        ['query'],
      ),
    'getAllAvailableBadges' : IDL.Func([], [IDL.Vec(Badge)], ['query']),
    'getAllCommunities' : IDL.Func([], [IDL.Vec(Community)], ['query']),
    'getBadgesByCommunity' : IDL.Func([IDL.Text], [IDL.Vec(Badge)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getClaimCodeDetails' : IDL.Func([IDL.Text], [IDL.Opt(Badge)], ['query']),
    'getClaimStatus' : IDL.Func(
        [IDL.Text],
        [
          IDL.Record({
            'errorMessage' : IDL.Opt(IDL.Text),
            'isClaimed' : IDL.Bool,
            'badge' : IDL.Opt(Badge),
            'isValid' : IDL.Bool,
          }),
        ],
        ['query'],
      ),
    'getCommunityBadgeCount' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'getCommunityClaimUrls' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
        ['query'],
      ),
    'getMostRecentBadge' : IDL.Func([], [IDL.Opt(UserBadge)], ['query']),
    'getMostRecentBadgeDetails' : IDL.Func(
        [],
        [IDL.Opt(IDL.Tuple(UserBadge, IDL.Opt(Badge), IDL.Opt(Community)))],
        ['query'],
      ),
    'getTotalBadges' : IDL.Func([], [IDL.Nat], ['query']),
    'getTotalCommunities' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserBadgeCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserBadgeDetails' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(UserBadge, IDL.Opt(Badge)))],
        ['query'],
      ),
    'getUserBadges' : IDL.Func([], [IDL.Vec(UserBadge)], ['query']),
    'getUserBadgesByCommunity' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Vec(UserBadge)))],
        ['query'],
      ),
    'getUserCommunities' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getUserCreatedCommunities' : IDL.Func([], [IDL.Vec(Community)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isBadgeClaimedByUser' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'validateClaimCode' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };