/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @dfinity/caffeine-bindgen@0.1.0-beta.7.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Badge {
  'id' : string,
  'communityId' : string,
  'displayCode' : string,
  'name' : string,
  'description' : string,
  'claimCode' : string,
  'imageUrl' : string,
  'quantity' : bigint,
  'claimedCount' : bigint,
}
export interface Community {
  'id' : string,
  'admin' : Principal,
  'name' : string,
}
export interface UserBadge {
  'communityId' : string,
  'claimedAt' : bigint,
  'badgeId' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addBadge' : ActorMethod<
    [string, string, string, string, string, bigint, string],
    string
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'claimBadge' : ActorMethod<[string], string>,
  'createCommunity' : ActorMethod<[string], string>,
  'getAdminBadgeAnalytics' : ActorMethod<
    [],
    Array<[Badge, bigint, bigint, Array<Principal>]>
  >,
  'getAdminBadgeClaimCodes' : ActorMethod<[], Array<[string, string]>>,
  'getAdminBadgeClaimUrls' : ActorMethod<[], Array<[string, string]>>,
  'getAllAvailableBadges' : ActorMethod<[], Array<Badge>>,
  'getAllCommunities' : ActorMethod<[], Array<Community>>,
  'getBadgesByCommunity' : ActorMethod<[string], Array<Badge>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getClaimCodeDetails' : ActorMethod<[string], [] | [Badge]>,
  'getClaimStatus' : ActorMethod<
    [string],
    {
      'errorMessage' : [] | [string],
      'isClaimed' : boolean,
      'badge' : [] | [Badge],
      'isValid' : boolean,
    }
  >,
  'getCommunityBadgeCount' : ActorMethod<[string], bigint>,
  'getCommunityClaimUrls' : ActorMethod<[string], Array<[string, string]>>,
  'getMostRecentBadge' : ActorMethod<[], [] | [UserBadge]>,
  'getMostRecentBadgeDetails' : ActorMethod<
    [],
    [] | [[UserBadge, [] | [Badge], [] | [Community]]]
  >,
  'getTotalBadges' : ActorMethod<[], bigint>,
  'getTotalCommunities' : ActorMethod<[], bigint>,
  'getUserBadgeCount' : ActorMethod<[], bigint>,
  'getUserBadgeDetails' : ActorMethod<[], Array<[UserBadge, [] | [Badge]]>>,
  'getUserBadges' : ActorMethod<[], Array<UserBadge>>,
  'getUserBadgesByCommunity' : ActorMethod<
    [],
    Array<[string, Array<UserBadge>]>
  >,
  'getUserCommunities' : ActorMethod<[], Array<string>>,
  'getUserCreatedCommunities' : ActorMethod<[], Array<Community>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isBadgeClaimedByUser' : ActorMethod<[string], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'validateClaimCode' : ActorMethod<[string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];